version: '3.8'

services:
  app:
    image: ghcr.io/rubenvitt/life-automations
    build: .
    restart: unless-stopped
    volumes:
      - data:/usr/src/app/data
    environment:
      NOTION_API_KEY: ${NOTION_API_KEY}
      TODOIST_API_KEY: ${TODOIST_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      CLIENT_API_REGISTRATION_KEY: ${CLIENT_API_REGISTRATION_KEY}
      FIREFLY_API_KEY: ${FIREFLY_API_KEY}
      FIREFLY_BASE_URI: ${FIREFLY_BASE_URI}
      NOTION_DAILY_REVIEWS_DB: ${NOTION_DAILY_REVIEWS_DB}
      TODOIST_DEFAULT_PROJECT: ${TODOIST_DEFAULT_PROJECT}
      NOTION_WEEKLY_REVIEWS_DB: ${NOTION_WEEKLY_REVIEWS_DB}
      NOTION_MONTHLY_REVIEWS_DB: ${NOTION_MONTHLY_REVIEWS_DB}
      NOTION_YEARLY_REVIEWS_DB: ${NOTION_YEARLY_REVIEWS_DB}
      NOTION_LONGTERM_REVIEWS_DB: ${NOTION_LONGTERM_REVIEWS_DB}
      NOTION_MOMENTS_DB: ${NOTION_MOMENTS_DB}
      NOTION_CONTRACTS_DB: ${NOTION_CONTRACTS_DB}
      NOTION_GOALS_DB: ${NOTION_GOALS_DB}
      NOTION_PROJECTS_DB: ${NOTION_PROJECTS_DB}
      NOTION_LEBENSBEREICHE_DB: ${NOTION_LEBENSBEREICHE_DB}
      NOTION_LAST_NEW_PROJECT_INITIAL: ${NOTION_LAST_NEW_PROJECT_INITIAL}
    ports:
      - "9003:3003"

volumes:
  data: