version: '3.8'

services:
  app:
    image: ghcr.io/rubenvitt/life-automations
    restart: always
    environment:
      NOTION_API_KEY: ${NOTION_API_KEY}
      TODOIST_API_KEY: ${TODOIST_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      CLIENT_API_REGISTRATION_KEY: ${CLIENT_API_REGISTRATION_KEY}
      FIREFLY_API_KEY: ${FIREFLY_API_KEY}
      FIREFLY_BASE_URI: ${FIREFLY_BASE_URI}
    ports:
      - "9003:3003"